# -*- coding: utf-8 -*-
"""Optical Character Recognition with EasyOCR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E_tvo3NKP9sC8a46lPo02ptgpm-T7Bp1
"""

!pip install easyocr

import numpy as np
import easyocr
import matplotlib.pyplot as plt
import cv2

img = cv2.imread("/content/images.jfif")
plt.imshow(img)

reader = easyocr.Reader(['en'])
result = reader.readtext(img)

result

topleft = result[0][0][0]
bottomright = result[0][0][2]

text = result[0][1]
font = cv2.FONT_HERSHEY_PLAIN

cv2.rectangle(img, topleft, bottomright, (255,0,255), thickness  = 3)
cv2.putText(img, text, topleft, font, fontScale = 1, color = (0, 255, 255))
plt.imshow(img)

img2 = cv2.imread("/content/reduce-speed-now-sign.png")
plt.imshow(img)

results = reader.readtext(img2)

results

for result in results:
  Top_left = result[0][0]
  Bottom_right = result[0][2]
  text = result[1]
  cv2.rectangle(img2, Top_left, Bottom_right, color = (255,255,0), thickness = 3)
  cv2.putText(img2, text, Top_left, font, fontScale = 3, color = (0,255,255),thickness = 3 )

plt.imshow(img2)

